name: badpunink
favicon: null
layout_spectrum: 0.4985674927011132
typography_spectrum: 0.3077116378117353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12575254496186972
  lightness: 0.3153431657701731
  saturation: 0.5811660701874644
  rhythmicContrast: 0.4285767204128206
purpose: []
